#### Importing Needed Libriries

In [20]:
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin


#### Creating Z-score Escalator

In [21]:
class MyStandardScaler(BaseEstimator, TransformerMixin):
    
    def fit(self, X, y=None):
        
        self.mean_ = np.mean(X, axis=0) ## Gets the mean of each feature
        self.std_scale = np.std(X - self.mean_, axis=0) ## divides every column by the STD
        
        return self
    def transform(self, X):
        # Scale features
        X_new = (X - self.mean_)/(self.std_scale)
        return X_new

#### Testing the created class and comparing w/ the sklearn StandardScaler

In [23]:
from sklearn.preprocessing import StandardScaler

A = np.array([[1, 1, 1], [2, 4, 8], [3, 9, 27], [4, 16, 64]])


### MyStandardScaler output
my_scaler = MyStandardScaler()
my_scaler.fit(A)
print(f'MyStandardScaler output: \n {my_scaler.transform(A)}\n')

### StandardScaler output
sk_scaler = StandardScaler()
sk_scaler.fit(A)
print(f'StandardScaler output: \n {sk_scaler.transform(A)}\n')

MyStandardScaler output: 
 [[-1.34164079 -1.14458618 -0.98184354]
 [-0.4472136  -0.61631563 -0.69547251]
 [ 0.4472136   0.26413527  0.08182029]
 [ 1.34164079  1.49676654  1.59549575]]

StandardScaler output: 
 [[-1.34164079 -1.14458618 -0.98184354]
 [-0.4472136  -0.61631563 -0.69547251]
 [ 0.4472136   0.26413527  0.08182029]
 [ 1.34164079  1.49676654  1.59549575]]

